		--- BOOTSTRAPPING FWEB with Sun/cc ---

  Please use gcc instead of cc if that's available on your system.  (If it's
not, you should get it; it's free, and it works.)

  One reason for using gcc is that its variable argument facilities conform
to ANSI C.  Sun's do not.  Although FWEB has been macroed up to accept
either convention, that code has not been tested thoroughly for the cc
version.  

  To bootstrap, please see the instructions in READ_ME.FWEB.
