.TH FWEB 1 "March 12, 1998"
.UC 4
.SH NAME
idxmerge \- merge fweb-produced index files.
.SH SYNOPSIS
.B idxmerge
-o\fIindex-file\fR file1.idx...
.br
.SH DESCRIPTION
.B idxmerge
merges index files produced by the invocation of
.B fweave
with option
.B -XI. 

.SH MANUAL
Further documentation can be obtained from texinfo, available online
through emacs' info browser (menu item
.B fweb
), or in HTML format.
.PP

.SH BUGS
Please send bug reports, suggestions, and questions to
.B krommes@princeton.edu.  
FWEB is a spare-time activity, so response may be slow.  However, your
input is very much appreciated.

.PP
.SH AUTHORS
.PP
.B idxmerge
was written by John A. Krommes, Princeton University, as part of the
.B FWEB
system.

This manpage was written by Yann Dirson \fI<dirson@debian.org>\fR
for the Debian Project, with information from the
.B FWEB
Texinfo manual.
